### ISSUE TITLE
Footer Blueprint collision after save

### ISSUE THREAD

**Issue by petira** [kittyfishfrommars/grav-theme-oxygen#4]
**Normal mode:**
```
Headline => social.title (unused)
```

vs.

**Expert mode:**
```
social:
    headline: => only in Expert mode (used in template)
    title: => Headline (unused)
```

---

**Normal mode:**
```
Byline => social.byline (unused, merged)
```

vs.

**Expert mode:**
```
social:
  byline: => Byline (unused, merged)
    class: => none (deleted)
    text: => none (deleted)
```
